#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OAI_ShippingRequest")]
public partial class ShippingRequestDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertShipping_Request(Shipping_Request instance);
  partial void UpdateShipping_Request(Shipping_Request instance);
  partial void DeleteShipping_Request(Shipping_Request instance);
  partial void InsertProcessed_Request(Processed_Request instance);
  partial void UpdateProcessed_Request(Processed_Request instance);
  partial void DeleteProcessed_Request(Processed_Request instance);
  #endregion
	
	public ShippingRequestDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OAI_ShippingRequestConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public ShippingRequestDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ShippingRequestDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ShippingRequestDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ShippingRequestDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Politcal_Subunit> Politcal_Subunits
	{
		get
		{
			return this.GetTable<Politcal_Subunit>();
		}
	}
	
	public System.Data.Linq.Table<Shipping_Request> Shipping_Requests
	{
		get
		{
			return this.GetTable<Shipping_Request>();
		}
	}
	
	public System.Data.Linq.Table<Processed_Request> Processed_Requests
	{
		get
		{
			return this.GetTable<Processed_Request>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Politcal_Subunits")]
public partial class Politcal_Subunit
{
	
	private string _IATA_Code;
	
	private string _Political_Unit_Code;
	
	private string _Political_Unit_Name;
	
	public Politcal_Subunit()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IATA_Code", DbType="NVarChar(5)")]
	public string IATA_Code
	{
		get
		{
			return this._IATA_Code;
		}
		set
		{
			if ((this._IATA_Code != value))
			{
				this._IATA_Code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Political_Unit_Code", DbType="NVarChar(10)")]
	public string Political_Unit_Code
	{
		get
		{
			return this._Political_Unit_Code;
		}
		set
		{
			if ((this._Political_Unit_Code != value))
			{
				this._Political_Unit_Code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Political_Unit_Name", DbType="NVarChar(50)")]
	public string Political_Unit_Name
	{
		get
		{
			return this._Political_Unit_Name;
		}
		set
		{
			if ((this._Political_Unit_Name != value))
			{
				this._Political_Unit_Name = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shipping_Request")]
public partial class Shipping_Request : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Ship_Type_Business_Private;
	
	private System.Nullable<System.DateTime> _ShipInitatingDate;
	
	private string _InitiatingDepartment;
	
	private string _From_Name;
	
	private string _To_Name;
	
	private string _To_Company;
	
	private string _To_Address_One;
	
	private string _To_Address_Two;
	
	private string _To_Phone;
	
	private string _From_Phone;
	
	private System.Nullable<System.DateTime> _Shipped_By_Date;
	
	private System.Nullable<System.TimeSpan> _Shipped_By_Time;
	
	private System.Nullable<bool> _Signature_Required;
	
	private string _Bill_To_Third_Party;
	
	private string _Logged_In_User;
	
	private string _Comments;
	
	private string _From_Email_Address;
	
	private string _To_Country;
	
	private string _To_City;
	
	private string _To_State;
	
	private string _To_Postal_Code;
	
	private string _Urgency;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnShip_Type_Business_PrivateChanging(string value);
    partial void OnShip_Type_Business_PrivateChanged();
    partial void OnShipInitatingDateChanging(System.Nullable<System.DateTime> value);
    partial void OnShipInitatingDateChanged();
    partial void OnInitiatingDepartmentChanging(string value);
    partial void OnInitiatingDepartmentChanged();
    partial void OnFrom_NameChanging(string value);
    partial void OnFrom_NameChanged();
    partial void OnTo_NameChanging(string value);
    partial void OnTo_NameChanged();
    partial void OnTo_CompanyChanging(string value);
    partial void OnTo_CompanyChanged();
    partial void OnTo_Address_OneChanging(string value);
    partial void OnTo_Address_OneChanged();
    partial void OnTo_Address_TwoChanging(string value);
    partial void OnTo_Address_TwoChanged();
    partial void OnTo_PhoneChanging(string value);
    partial void OnTo_PhoneChanged();
    partial void OnFrom_PhoneChanging(string value);
    partial void OnFrom_PhoneChanged();
    partial void OnShipped_By_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnShipped_By_DateChanged();
    partial void OnShipped_By_TimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnShipped_By_TimeChanged();
    partial void OnSignature_RequiredChanging(System.Nullable<bool> value);
    partial void OnSignature_RequiredChanged();
    partial void OnBill_To_Third_PartyChanging(string value);
    partial void OnBill_To_Third_PartyChanged();
    partial void OnLogged_In_UserChanging(string value);
    partial void OnLogged_In_UserChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    partial void OnFrom_Email_AddressChanging(string value);
    partial void OnFrom_Email_AddressChanged();
    partial void OnTo_CountryChanging(string value);
    partial void OnTo_CountryChanged();
    partial void OnTo_CityChanging(string value);
    partial void OnTo_CityChanged();
    partial void OnTo_StateChanging(string value);
    partial void OnTo_StateChanged();
    partial void OnTo_Postal_CodeChanging(string value);
    partial void OnTo_Postal_CodeChanged();
    partial void OnUrgencyChanging(string value);
    partial void OnUrgencyChanged();
    #endregion
	
	public Shipping_Request()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ship_Type_Business_Private", DbType="NVarChar(9)")]
	public string Ship_Type_Business_Private
	{
		get
		{
			return this._Ship_Type_Business_Private;
		}
		set
		{
			if ((this._Ship_Type_Business_Private != value))
			{
				this.OnShip_Type_Business_PrivateChanging(value);
				this.SendPropertyChanging();
				this._Ship_Type_Business_Private = value;
				this.SendPropertyChanged("Ship_Type_Business_Private");
				this.OnShip_Type_Business_PrivateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipInitatingDate", DbType="Date")]
	public System.Nullable<System.DateTime> ShipInitatingDate
	{
		get
		{
			return this._ShipInitatingDate;
		}
		set
		{
			if ((this._ShipInitatingDate != value))
			{
				this.OnShipInitatingDateChanging(value);
				this.SendPropertyChanging();
				this._ShipInitatingDate = value;
				this.SendPropertyChanged("ShipInitatingDate");
				this.OnShipInitatingDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitiatingDepartment", DbType="NVarChar(50)")]
	public string InitiatingDepartment
	{
		get
		{
			return this._InitiatingDepartment;
		}
		set
		{
			if ((this._InitiatingDepartment != value))
			{
				this.OnInitiatingDepartmentChanging(value);
				this.SendPropertyChanging();
				this._InitiatingDepartment = value;
				this.SendPropertyChanged("InitiatingDepartment");
				this.OnInitiatingDepartmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From_Name", DbType="NVarChar(50)")]
	public string From_Name
	{
		get
		{
			return this._From_Name;
		}
		set
		{
			if ((this._From_Name != value))
			{
				this.OnFrom_NameChanging(value);
				this.SendPropertyChanging();
				this._From_Name = value;
				this.SendPropertyChanged("From_Name");
				this.OnFrom_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Name", DbType="NVarChar(50)")]
	public string To_Name
	{
		get
		{
			return this._To_Name;
		}
		set
		{
			if ((this._To_Name != value))
			{
				this.OnTo_NameChanging(value);
				this.SendPropertyChanging();
				this._To_Name = value;
				this.SendPropertyChanged("To_Name");
				this.OnTo_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Company", DbType="NVarChar(50)")]
	public string To_Company
	{
		get
		{
			return this._To_Company;
		}
		set
		{
			if ((this._To_Company != value))
			{
				this.OnTo_CompanyChanging(value);
				this.SendPropertyChanging();
				this._To_Company = value;
				this.SendPropertyChanged("To_Company");
				this.OnTo_CompanyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Address_One", DbType="NVarChar(50)")]
	public string To_Address_One
	{
		get
		{
			return this._To_Address_One;
		}
		set
		{
			if ((this._To_Address_One != value))
			{
				this.OnTo_Address_OneChanging(value);
				this.SendPropertyChanging();
				this._To_Address_One = value;
				this.SendPropertyChanged("To_Address_One");
				this.OnTo_Address_OneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Address_Two", DbType="NVarChar(50)")]
	public string To_Address_Two
	{
		get
		{
			return this._To_Address_Two;
		}
		set
		{
			if ((this._To_Address_Two != value))
			{
				this.OnTo_Address_TwoChanging(value);
				this.SendPropertyChanging();
				this._To_Address_Two = value;
				this.SendPropertyChanged("To_Address_Two");
				this.OnTo_Address_TwoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Phone", DbType="NVarChar(50)")]
	public string To_Phone
	{
		get
		{
			return this._To_Phone;
		}
		set
		{
			if ((this._To_Phone != value))
			{
				this.OnTo_PhoneChanging(value);
				this.SendPropertyChanging();
				this._To_Phone = value;
				this.SendPropertyChanged("To_Phone");
				this.OnTo_PhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From_Phone", DbType="NVarChar(50)")]
	public string From_Phone
	{
		get
		{
			return this._From_Phone;
		}
		set
		{
			if ((this._From_Phone != value))
			{
				this.OnFrom_PhoneChanging(value);
				this.SendPropertyChanging();
				this._From_Phone = value;
				this.SendPropertyChanged("From_Phone");
				this.OnFrom_PhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shipped_By_Date", DbType="Date")]
	public System.Nullable<System.DateTime> Shipped_By_Date
	{
		get
		{
			return this._Shipped_By_Date;
		}
		set
		{
			if ((this._Shipped_By_Date != value))
			{
				this.OnShipped_By_DateChanging(value);
				this.SendPropertyChanging();
				this._Shipped_By_Date = value;
				this.SendPropertyChanged("Shipped_By_Date");
				this.OnShipped_By_DateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shipped_By_Time", DbType="Time")]
	public System.Nullable<System.TimeSpan> Shipped_By_Time
	{
		get
		{
			return this._Shipped_By_Time;
		}
		set
		{
			if ((this._Shipped_By_Time != value))
			{
				this.OnShipped_By_TimeChanging(value);
				this.SendPropertyChanging();
				this._Shipped_By_Time = value;
				this.SendPropertyChanged("Shipped_By_Time");
				this.OnShipped_By_TimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Signature_Required", DbType="Bit")]
	public System.Nullable<bool> Signature_Required
	{
		get
		{
			return this._Signature_Required;
		}
		set
		{
			if ((this._Signature_Required != value))
			{
				this.OnSignature_RequiredChanging(value);
				this.SendPropertyChanging();
				this._Signature_Required = value;
				this.SendPropertyChanged("Signature_Required");
				this.OnSignature_RequiredChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bill_To_Third_Party", DbType="NVarChar(50)")]
	public string Bill_To_Third_Party
	{
		get
		{
			return this._Bill_To_Third_Party;
		}
		set
		{
			if ((this._Bill_To_Third_Party != value))
			{
				this.OnBill_To_Third_PartyChanging(value);
				this.SendPropertyChanging();
				this._Bill_To_Third_Party = value;
				this.SendPropertyChanged("Bill_To_Third_Party");
				this.OnBill_To_Third_PartyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logged_In_User", DbType="NVarChar(50)")]
	public string Logged_In_User
	{
		get
		{
			return this._Logged_In_User;
		}
		set
		{
			if ((this._Logged_In_User != value))
			{
				this.OnLogged_In_UserChanging(value);
				this.SendPropertyChanging();
				this._Logged_In_User = value;
				this.SendPropertyChanged("Logged_In_User");
				this.OnLogged_In_UserChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="NVarChar(MAX)")]
	public string Comments
	{
		get
		{
			return this._Comments;
		}
		set
		{
			if ((this._Comments != value))
			{
				this.OnCommentsChanging(value);
				this.SendPropertyChanging();
				this._Comments = value;
				this.SendPropertyChanged("Comments");
				this.OnCommentsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From_Email_Address", DbType="NVarChar(50)")]
	public string From_Email_Address
	{
		get
		{
			return this._From_Email_Address;
		}
		set
		{
			if ((this._From_Email_Address != value))
			{
				this.OnFrom_Email_AddressChanging(value);
				this.SendPropertyChanging();
				this._From_Email_Address = value;
				this.SendPropertyChanged("From_Email_Address");
				this.OnFrom_Email_AddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Country", DbType="NVarChar(50)")]
	public string To_Country
	{
		get
		{
			return this._To_Country;
		}
		set
		{
			if ((this._To_Country != value))
			{
				this.OnTo_CountryChanging(value);
				this.SendPropertyChanging();
				this._To_Country = value;
				this.SendPropertyChanged("To_Country");
				this.OnTo_CountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_City", DbType="NVarChar(50)")]
	public string To_City
	{
		get
		{
			return this._To_City;
		}
		set
		{
			if ((this._To_City != value))
			{
				this.OnTo_CityChanging(value);
				this.SendPropertyChanging();
				this._To_City = value;
				this.SendPropertyChanged("To_City");
				this.OnTo_CityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_State", DbType="NVarChar(50)")]
	public string To_State
	{
		get
		{
			return this._To_State;
		}
		set
		{
			if ((this._To_State != value))
			{
				this.OnTo_StateChanging(value);
				this.SendPropertyChanging();
				this._To_State = value;
				this.SendPropertyChanged("To_State");
				this.OnTo_StateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Postal_Code", DbType="NVarChar(20)")]
	public string To_Postal_Code
	{
		get
		{
			return this._To_Postal_Code;
		}
		set
		{
			if ((this._To_Postal_Code != value))
			{
				this.OnTo_Postal_CodeChanging(value);
				this.SendPropertyChanging();
				this._To_Postal_Code = value;
				this.SendPropertyChanged("To_Postal_Code");
				this.OnTo_Postal_CodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Urgency", DbType="NVarChar(50)")]
	public string Urgency
	{
		get
		{
			return this._Urgency;
		}
		set
		{
			if ((this._Urgency != value))
			{
				this.OnUrgencyChanging(value);
				this.SendPropertyChanging();
				this._Urgency = value;
				this.SendPropertyChanged("Urgency");
				this.OnUrgencyChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Processed_Requests")]
public partial class Processed_Request : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Total_Cost;
	
	private string _Tracking_Num;
	
	private string _To_Company;
	
	private string _To_Name;
	
	private string _To_AddOne;
	
	private string _To_AddTwo;
	
	private string _To_City;
	
	private string _To_State;
	
	private string _To_Country;
	
	private string _To_Telephone;
	
	private string _To_PostalCode;
	
	private string _From_Name;
	
	private string _From_Phone;
	
	private System.Nullable<System.DateTime> _Ship_InitDate;
	
	private string _Original_ShipID;
	
	private string _Payroll_Status;
	
	private string _Ship_Type;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTotal_CostChanging(string value);
    partial void OnTotal_CostChanged();
    partial void OnTracking_NumChanging(string value);
    partial void OnTracking_NumChanged();
    partial void OnTo_CompanyChanging(string value);
    partial void OnTo_CompanyChanged();
    partial void OnTo_NameChanging(string value);
    partial void OnTo_NameChanged();
    partial void OnTo_AddOneChanging(string value);
    partial void OnTo_AddOneChanged();
    partial void OnTo_AddTwoChanging(string value);
    partial void OnTo_AddTwoChanged();
    partial void OnTo_CityChanging(string value);
    partial void OnTo_CityChanged();
    partial void OnTo_StateChanging(string value);
    partial void OnTo_StateChanged();
    partial void OnTo_CountryChanging(string value);
    partial void OnTo_CountryChanged();
    partial void OnTo_TelephoneChanging(string value);
    partial void OnTo_TelephoneChanged();
    partial void OnTo_PostalCodeChanging(string value);
    partial void OnTo_PostalCodeChanged();
    partial void OnFrom_NameChanging(string value);
    partial void OnFrom_NameChanged();
    partial void OnFrom_PhoneChanging(string value);
    partial void OnFrom_PhoneChanged();
    partial void OnShip_InitDateChanging(System.Nullable<System.DateTime> value);
    partial void OnShip_InitDateChanged();
    partial void OnOriginal_ShipIDChanging(string value);
    partial void OnOriginal_ShipIDChanged();
    partial void OnPayroll_StatusChanging(string value);
    partial void OnPayroll_StatusChanged();
    partial void OnShip_TypeChanging(string value);
    partial void OnShip_TypeChanged();
    #endregion
	
	public Processed_Request()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Cost", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
	public string Total_Cost
	{
		get
		{
			return this._Total_Cost;
		}
		set
		{
			if ((this._Total_Cost != value))
			{
				this.OnTotal_CostChanging(value);
				this.SendPropertyChanging();
				this._Total_Cost = value;
				this.SendPropertyChanged("Total_Cost");
				this.OnTotal_CostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tracking_Num", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Tracking_Num
	{
		get
		{
			return this._Tracking_Num;
		}
		set
		{
			if ((this._Tracking_Num != value))
			{
				this.OnTracking_NumChanging(value);
				this.SendPropertyChanging();
				this._Tracking_Num = value;
				this.SendPropertyChanged("Tracking_Num");
				this.OnTracking_NumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Company", DbType="NVarChar(10)")]
	public string To_Company
	{
		get
		{
			return this._To_Company;
		}
		set
		{
			if ((this._To_Company != value))
			{
				this.OnTo_CompanyChanging(value);
				this.SendPropertyChanging();
				this._To_Company = value;
				this.SendPropertyChanged("To_Company");
				this.OnTo_CompanyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Name", DbType="NVarChar(50)")]
	public string To_Name
	{
		get
		{
			return this._To_Name;
		}
		set
		{
			if ((this._To_Name != value))
			{
				this.OnTo_NameChanging(value);
				this.SendPropertyChanging();
				this._To_Name = value;
				this.SendPropertyChanged("To_Name");
				this.OnTo_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_AddOne", DbType="NVarChar(50)")]
	public string To_AddOne
	{
		get
		{
			return this._To_AddOne;
		}
		set
		{
			if ((this._To_AddOne != value))
			{
				this.OnTo_AddOneChanging(value);
				this.SendPropertyChanging();
				this._To_AddOne = value;
				this.SendPropertyChanged("To_AddOne");
				this.OnTo_AddOneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_AddTwo", DbType="NChar(50)")]
	public string To_AddTwo
	{
		get
		{
			return this._To_AddTwo;
		}
		set
		{
			if ((this._To_AddTwo != value))
			{
				this.OnTo_AddTwoChanging(value);
				this.SendPropertyChanging();
				this._To_AddTwo = value;
				this.SendPropertyChanged("To_AddTwo");
				this.OnTo_AddTwoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_City", DbType="NVarChar(50)")]
	public string To_City
	{
		get
		{
			return this._To_City;
		}
		set
		{
			if ((this._To_City != value))
			{
				this.OnTo_CityChanging(value);
				this.SendPropertyChanging();
				this._To_City = value;
				this.SendPropertyChanged("To_City");
				this.OnTo_CityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_State", DbType="NVarChar(50)")]
	public string To_State
	{
		get
		{
			return this._To_State;
		}
		set
		{
			if ((this._To_State != value))
			{
				this.OnTo_StateChanging(value);
				this.SendPropertyChanging();
				this._To_State = value;
				this.SendPropertyChanged("To_State");
				this.OnTo_StateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Country", DbType="NVarChar(50)")]
	public string To_Country
	{
		get
		{
			return this._To_Country;
		}
		set
		{
			if ((this._To_Country != value))
			{
				this.OnTo_CountryChanging(value);
				this.SendPropertyChanging();
				this._To_Country = value;
				this.SendPropertyChanged("To_Country");
				this.OnTo_CountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Telephone", DbType="NVarChar(50)")]
	public string To_Telephone
	{
		get
		{
			return this._To_Telephone;
		}
		set
		{
			if ((this._To_Telephone != value))
			{
				this.OnTo_TelephoneChanging(value);
				this.SendPropertyChanging();
				this._To_Telephone = value;
				this.SendPropertyChanged("To_Telephone");
				this.OnTo_TelephoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_PostalCode", DbType="NVarChar(50)")]
	public string To_PostalCode
	{
		get
		{
			return this._To_PostalCode;
		}
		set
		{
			if ((this._To_PostalCode != value))
			{
				this.OnTo_PostalCodeChanging(value);
				this.SendPropertyChanging();
				this._To_PostalCode = value;
				this.SendPropertyChanged("To_PostalCode");
				this.OnTo_PostalCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From_Name", DbType="NVarChar(50)")]
	public string From_Name
	{
		get
		{
			return this._From_Name;
		}
		set
		{
			if ((this._From_Name != value))
			{
				this.OnFrom_NameChanging(value);
				this.SendPropertyChanging();
				this._From_Name = value;
				this.SendPropertyChanged("From_Name");
				this.OnFrom_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From_Phone", DbType="NVarChar(50)")]
	public string From_Phone
	{
		get
		{
			return this._From_Phone;
		}
		set
		{
			if ((this._From_Phone != value))
			{
				this.OnFrom_PhoneChanging(value);
				this.SendPropertyChanging();
				this._From_Phone = value;
				this.SendPropertyChanged("From_Phone");
				this.OnFrom_PhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ship_InitDate", DbType="Date")]
	public System.Nullable<System.DateTime> Ship_InitDate
	{
		get
		{
			return this._Ship_InitDate;
		}
		set
		{
			if ((this._Ship_InitDate != value))
			{
				this.OnShip_InitDateChanging(value);
				this.SendPropertyChanging();
				this._Ship_InitDate = value;
				this.SendPropertyChanged("Ship_InitDate");
				this.OnShip_InitDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Original_ShipID", DbType="NVarChar(20)")]
	public string Original_ShipID
	{
		get
		{
			return this._Original_ShipID;
		}
		set
		{
			if ((this._Original_ShipID != value))
			{
				this.OnOriginal_ShipIDChanging(value);
				this.SendPropertyChanging();
				this._Original_ShipID = value;
				this.SendPropertyChanged("Original_ShipID");
				this.OnOriginal_ShipIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payroll_Status", DbType="NChar(20) NOT NULL", CanBeNull=false)]
	public string Payroll_Status
	{
		get
		{
			return this._Payroll_Status;
		}
		set
		{
			if ((this._Payroll_Status != value))
			{
				this.OnPayroll_StatusChanging(value);
				this.SendPropertyChanging();
				this._Payroll_Status = value;
				this.SendPropertyChanged("Payroll_Status");
				this.OnPayroll_StatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ship_Type", DbType="NVarChar(1)")]
	public string Ship_Type
	{
		get
		{
			return this._Ship_Type;
		}
		set
		{
			if ((this._Ship_Type != value))
			{
				this.OnShip_TypeChanging(value);
				this.SendPropertyChanging();
				this._Ship_Type = value;
				this.SendPropertyChanged("Ship_Type");
				this.OnShip_TypeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
